#!/bin/sh

echo "Welcome to another awesome autistic art by Daniella Mesquita. Edit by crysil to make linux icons"

processicons () {
echo ""

if [ "$is_interactive" != "true" ]; then
echo "Write your icons export path"
read path
fi

if [ ! -e icons ]; then mkdir $path/icons; fi
if [ ! -e icons/16x16 ]; then mkdir $path/icons/16x16; fi
if [ ! -e icons/24x24 ]; then mkdir $path/icons/24x24; fi
if [ ! -e icons/32x32 ]; then mkdir $path/icons/32x32; fi
if [ ! -e icons/48x48 ]; then mkdir $path/icons/48x48; fi
if [ ! -e icons/64x64 ]; then mkdir $path/icons/64x64; fi
if [ ! -e icons/96x96 ]; then mkdir $path/icons/96x96; fi

if [ "$is_interactive" != "true" ]; then
echo "Bellow, please write the name.extension of the source image (if it isn't in this same folder, write the full path) file you want to convert into Linux icon."
echo "Minimum dimensions: 512x512 🧗"

echo -n "Please write the file path/name.extension:"
read imgname
fi
if [ $(identify -ping -format '%w' "$imgname") -ge 512 ]; then
    echo "Confirmed, it meets the minimum dimensions. File dimensions: $(identify -ping -format '%w' "$imgname")x$(identify -ping -format '%w' "$imgname") 🙌"
    if [ "$is_interactive" != "true" ]; then
    echo -n "Please write the name.extension you want for your icon:"
    read applyname
fi
    echo "Ok, working... 👩‍🏭"
    convert "$imgname"    -resize 16x16  $path/icons/16x16/$applyname
    convert "$imgname"    -resize 32x32  $path/icons/32x32/$applyname
    convert "$imgname"    -resize 24x24  $path/icons/24x24/$applyname
    convert "$imgname"    -resize 48x48  $path/icons/48x48/$applyname
    convert "$imgname"    -resize 32x32  $path/icons/32x32/$applyname
    convert "$imgname"    -resize 64x64  $path/icons/64x64/$applyname
    convert "$imgname"    -resize 96x96  $path/icons/96x96/$applyname
    echo "Done! Kisses 😘"
    
    echo "Zipping files..."
    zip -r $path/icons.zip $path/icons
    else
        echo "Oh, error 🤷 Please review how you've wrote/copied the file name."
    echo -n "Exit"
fi
}


if [ "$1" = "" ]; then
   is_interactive=""
   processicons
else
   is_interactive="true"
   imgname=""$1""
   path="$2"
   applyname=""$3""
   processicons
fi
